version: '3.8'

services:
  deepseek-ocr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepseek-ocr-api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OCR_MODE=${OCR_MODE:-local}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=${DEEPSEEK_API_URL}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-10}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES:-jpg,jpeg,png,pdf}
      - TEMP_DIR=/app/temp
      - PYTHON_PATH=python3
      - DEEPSEEK_MODEL_PATH=${DEEPSEEK_MODEL_PATH:-deepseek-ai/DeepSeek-OCR}
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/ocr/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

